const constants = {
  FETCH_CONTACT: 'FETCH_CONTACTS',
  ADD_CONTACT: 'ADD_CONTACT',
  EDIT_CONTACT: 'EDIT_CONTACT',
  REMOVE_CONTACT: 'REMOVE_CONTACT',
  LOAD_CONTACTS: 'LOAD_CONTACTS',
  ADD_ERROR: 'ADD_ERROR',
  CLEAR_ERROR: 'CLEAR_ERROR',
  FETCHING_CONTACTS: 'FETCHING_CONTACTS',
  CANCEL_FETCHING: 'CANCEL_FETCHING',
  CHANGE_SUGGESTIONS: 'CHANGE_SUGGESTIONS',
  CLEAR_SUGGESTIONS: 'CLEAR_SUGGESTIONS',
  SET_GOAL: 'SET_GOAL'
};

export default constants;
